import type { Metadata } from "next";
import { Old_Standard_TT, Caveat, Roboto } from "next/font/google";
// import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import "./globals.css";


// main font style
const mainScript = Old_Standard_TT({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-main",
});

// caption font style
const captionScript = Caveat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-caption",
});

// decription font style
const textScript = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-text",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainScript.variable} ${captionScript.variable} ${textScript.variable} font-main`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
